CRITICAL - 2022-01-09 10:21:38 --> CodeIgniter\BaseModel::transformDataToArray(): Return value must be of type array, int returned
#0 D:\xampp\htdocs\NPOS\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(1, 'insert')
#1 D:\xampp\htdocs\NPOS\system\Model.php(620): CodeIgniter\BaseModel->insert(1, false)
#2 D:\xampp\htdocs\NPOS\system\BaseModel.php(658): CodeIgniter\Model->insert(1, false)
#3 D:\xampp\htdocs\NPOS\app\Controllers\Home.php(31): CodeIgniter\BaseModel->save(1, Array)
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Home->testadd()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-09 10:24:06 --> CodeIgniter\BaseModel::transformDataToArray(): Return value must be of type array, string returned
#0 D:\xampp\htdocs\NPOS\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray('1', 'insert')
#1 D:\xampp\htdocs\NPOS\system\Model.php(620): CodeIgniter\BaseModel->insert('1', false)
#2 D:\xampp\htdocs\NPOS\system\BaseModel.php(658): CodeIgniter\Model->insert('1', false)
#3 D:\xampp\htdocs\NPOS\app\Controllers\Home.php(31): CodeIgniter\BaseModel->save('1', Array)
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Home->testadd()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-09 10:36:12 --> Undefined variable $setting_data
#0 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'D:\\xampp\\htdocs...', 14)
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(801): App\Controllers\Setting->__construct()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 10:36:40 --> Undefined variable $setting_data
#0 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'D:\\xampp\\htdocs...', 14)
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(801): App\Controllers\Setting->__construct()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 11:47:52 --> file_get_contents(D:\xampp\htdocs\NPOS\writable\uploads/sample/image.png): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 47)
#1 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(47): file_get_contents('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-01-09 11:48:48 --> file_get_contents(D:\xampp\htdocs\NPOS\writable\uploads/sample/image.png): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 47)
#1 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(47): file_get_contents('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-01-09 11:49:56 --> file_get_contents(D:\xampp\htdocs\NPOS\writable\uploads/sample/image.png): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 47)
#1 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(47): file_get_contents('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-01-09 11:50:34 --> file_get_contents(D:\xampp\htdocs\NPOS\writable\uploads/qrcode/): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 45)
#1 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(45): file_get_contents('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-01-09 11:52:14 --> file_get_contents(D:\xampp\htdocs\NPOS\writable\uploads/sample/image.png): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 47)
#1 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(47): file_get_contents('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#4 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-01-09 12:20:16 --> Attempt to read property "setting_bank_qrcode" on null
#0 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'D:\\xampp\\htdocs...', 44)
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 12:20:38 --> Attempt to read property "setting_bank_qrcode" on null
#0 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'D:\\xampp\\htdocs...', 44)
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->qrcode_img()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-01-09 12:40:52 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:41:21 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:41:48 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:44:27 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:44:34 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:46:28 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:48:44 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:48:53 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:49:56 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:50:53 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:51:06 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 12:51:17 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 13:02:24 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 13:04:51 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 13:04:55 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2022-01-09 13:16:34 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
CRITICAL - 2022-01-09 13:41:49 --> Call to undefined function App\Controllers\appDirectory()
#0 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-01-09 13:42:28 --> Undefined constant "App\Controllers\appDirectory"
#0 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-01-09 13:42:29 --> Undefined constant "App\Controllers\appDirectory"
#0 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-01-09 13:42:49 --> Undefined property: App\Controllers\Dashboard::$appDirectory
#0 D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'D:\\xampp\\htdocs...', 31)
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 13:42:50 --> Undefined property: App\Controllers\Dashboard::$appDirectory
#0 D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'D:\\xampp\\htdocs...', 31)
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 13:51:35 --> syntax error, unexpected token ","
#0 D:\xampp\htdocs\NPOS\system\Router\Router.php(176): CodeIgniter\Router\Router->autoRoute('dashboard')
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(718): CodeIgniter\Router\Router->handle('dashboard')
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 14:02:15 --> write_file(): Argument #2 ($data) must be of type string, null given, called in D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php on line 176
#0 D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php(176): write_file('D:\\xampp\\htdocs...', NULL, 'c')
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 14:03:34 --> write_file(): Argument #2 ($data) must be of type string, null given, called in D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php on line 176
#0 D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php(176): write_file('D:\\xampp\\htdocs...', NULL, 'c')
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-09 14:03:36 --> write_file(): Argument #2 ($data) must be of type string, null given, called in D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php on line 176
#0 D:\xampp\htdocs\NPOS\app\Controllers\Dashboard.php(176): write_file('D:\\xampp\\htdocs...', NULL, 'c')
#1 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#2 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#3 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-01-09 14:21:25 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:21:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:21:30 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:21:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:03 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:03 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:23 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:24 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:27 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:37 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:38 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:51 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:22:52 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:22:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:23:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:23:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:23:11 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:23:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:23:42 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:23:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:23:51 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:23:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:24:28 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:24:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:24:29 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:24:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:24:38 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:24:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:24:56 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:24:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:26:26 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:26:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:26:27 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:26:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:26:27 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:26:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:26:27 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:26:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:26:57 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:26:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:26:59 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:26:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:27:44 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:27:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-09 14:29:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-09 14:29:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\NPOS\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\NPOS\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\NPOS\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\NPOS\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\NPOS\app\Controllers\Setting.php(54): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(824): App\Controllers\Setting->ENV()
#6 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setting))
#7 D:\xampp\htdocs\NPOS\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\NPOS\public\index.php(48): CodeIgniter\CodeIgniter->run()
#9 {main}
